# Generated by Django 3.0.8 on 2020-08-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourite_dog_breed',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
