# Generated by Django 3.0.8 on 2020-08-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200831_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourite_dog_breed',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
