# Generated by Django 3.0.8 on 2020-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200831_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_cupcake_flavour',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
