# Generated by Django 3.0.8 on 2020-08-24 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
